/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  designer: [
    'intro',
    'designer/quick-start',
    {
      type: 'category',
      label: '接入指南',
      items: ['designer/deploy/designer', 'designer/deploy/sandbox', 'designer/deploy/server'],
      collapsed: false,
    },
    {
      type: 'category',
      label: '设计器自定义',
      items: [
        'designer/customize/panels',
        'designer/customize/tools',
        'designer/customize/sidebar',
        'designer/customize/setters',
        'designer/customize/editor',
        'designer/customize/components',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '设计原理',
      items: ['designer/design/overview', 'designer/design/filesystem', 'designer/design/sandbox'],
      collapsed: false,
    },
  ],

  boot: [
    'boot/intro',
    'boot/app-spec',
    'boot/tango-config',
    'boot/app',
    'boot/service',
    'boot/store',
    'boot/page',
    'boot/global',
    // 'boot/helpers',
    // 'boot/model',
    // 'boot/ref',
    // 'boot/i18n',
  ],

  // protocol: ['protocol/material-protocol', 'protocol/material-package-spec'],
};

module.exports = sidebars;
